grimuar/urls.py
from django.contrib import admin
from django.urls import path, include
from spell import views as spell_views
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', user_views.home, name="home"),

    # Spells
    path('create-spell/', spell_views.create_spell, name="create_spell"),

    # Auth
    path('signup/', user_views.signup_user, name="signup_user"),
    path('login/', user_views.login_user, name="login_user"),
    path('logout/', user_views.logout_user, name="logout_user"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.show_user_info, name="show_user_info"),
]

spell/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.html import mark_safe
from django.core.files.images import get_image_dimensions
from ckeditor.fields import RichTextField

# Create your models here.
class Spell_school(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="spell/images")
    alt = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title

    @property
    def image_preview(self):

        if self.image:
            width, height = get_image_dimensions(self.image)
            return mark_safe('<img src="{}" width="{}" height="{}" class="admin-image-shop" />'.format(self.image.url, width, height))
        return ''

    class Meta:
        verbose_name = _("Spell school")
        verbose_name_plural = _("Spell schools")

# Komponenty
class Components(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class Spell(models.Model):
    SPELL_LEVEL_CHOICES = [
        ('0', 'sztuczka'),
        ('1', '1. krąg'),
        ('2', '2. krąg'),
        ('3', '3. krąg'),
        ('4', '4. krąg'),
        ('5', '5. krąg'),
        ('6', '6. krąg'),
        ('7', '7. krąg'),
        ('8', '8. krąg'),
        ('9', '9. krąg'),
    ]

    ONE_ACTION = 1
    ONE_BONUS_ACTION = 2
    ONE_REACTION = 3
    ONE_MINUTE = 4
    TEN_MINUTES = 5
    ONE_HOUR = 6
    EIGHT_HOURS = 7
    TWELVE_HOURS = 8
    TWENTY_FOUR_HOURS = 9
    INSTANTANEOUS = 10
    UNTIL_DISPELED = 11
    ONE_ROUND = 12
    ONE_DAY = 13
    SEVEN_DAYS = 14
    TEN_DAYS = 15
    THIRTY_DAYS = 16
    SPECIAL = 17
    
    
    DURATION_TIME_CHOICES = [
        (INSTANTANEOUS, 'natychmiastowy'),
        (ONE_ROUND, '1 runda'),
        (ONE_MINUTE, '1 minuta'),
        (TEN_MINUTES, '10 minut'),
        (ONE_HOUR, '1 godzina'),
        (EIGHT_HOURS, '8 godzin'),
        (TWENTY_FOUR_HOURS, '24 godziny'),
        (SEVEN_DAYS, '7 dni'),
        (TEN_DAYS, '10 dni'),
        (THIRTY_DAYS, '30 dni'),
        (SPECIAL, 'specjalny'),
        (UNTIL_DISPELED, 'do rozproszenia'),
    ]

    CASTING_TIME_CHOICES = [
        (ONE_ACTION, '1 akcja'),
        (ONE_BONUS_ACTION, '1 akcja dodatkowa'),
        (ONE_REACTION, 'reakcja'),
        (ONE_MINUTE, '1 minuta'),
        (TEN_MINUTES, '10 minut'),
        (ONE_HOUR, '1 godzina'),
        (EIGHT_HOURS, '8 godzin'),
        (TWELVE_HOURS, '12 godzin'),
        (TWENTY_FOUR_HOURS, '24 godziny'),
    ]

    title = models.CharField(max_length=200)
    spell_school = models.ForeignKey(Spell_school, on_delete=models.SET_NULL, null=True)
    description = RichTextField(blank=True, null=True)
    higher_level = models.TextField(blank=True)
    spell_level = models.CharField(max_length=1, choices=SPELL_LEVEL_CHOICES, default=0)
    casting_time = models.IntegerField(choices=CASTING_TIME_CHOICES, default=ONE_ACTION)
    duration = models.IntegerField(choices=DURATION_TIME_CHOICES, default=ONE_ACTION)
    distance = models.CharField(max_length=50, blank=True)
    material_description = models.CharField(max_length=200, blank=True)
    concentration = models.BooleanField(default=False, blank=True)
    ritual = models.BooleanField(default=False, blank=True)
    components = models.ManyToManyField(Components, blank=True)

    def __str__(self):
        return self.title

    def is_verbal(self):
        if self.components.filter(title="Werbalny").exists():
            return True
        return False

    def is_somatic(self):
        if self.components.filter(title="Somatyczny").exists():
            return True
        return False
    
    def is_material(self):
        if self.components.filter(title="Materialny").exists():
            return True
        return False

spell/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField, CheckboxSelectMultiple
from .models import Spell, Components

class SpellForm(ModelForm):
    class Meta:
        model = Spell
        fields = [
            'title',
            'spell_school',
            'description',
            'higher_level',
            'spell_level',
            'casting_time',
            'duration',
            'components',
            'material_description',
            'concentration',
            'ritual',
        ]

    components = ModelMultipleChoiceField(
        queryset=Components.objects.all(),
        widget=CheckboxSelectMultiple
    )

spell/views.py
from django.shortcuts import render, redirect
from .forms import SpellForm
from django.contrib.auth.decorators import login_required, user_passes_test

# Create your views here.
def show_all_spells(request):
    return render(request, 'spell/show_all_spells.html')

@login_required
@user_passes_test(lambda u: u.groups.filter(name='Editor').exists())
def create_spell(request):
    if request.method == "GET":
        return render(request, 'spell/create_spell.html', {'form' : SpellForm()})
    else:
        try:
            form = SpellForm(request.POST)
            form.is_valid()
            form.save()
            return render(request, 'spell/create_spell.html', {'form' : SpellForm(), 'alert' : 'Zaklecie zostalo dodane poprawnie.'})
        except ValueError:
            return render(request, 'spell/create_spell.html', {'form' : SpellForm(), 'error' : form.errors })
        

spell/templates/spell/create_spell.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Stwórz zaklęcie{% endblock %}

{% block content %}
<div class="row justify-content-center mt-1">
    <div class="col-md-9 paper-background">
        {% if alert %}
        <div class="alert alert-success" role="alert">
            {{ alert }}
        </div>
        {% endif %}
        {% if error %}
        <div class="alert alert-danger" role="alert">
            <h4 class="text-center">Błąd!</h4>
            {% if error.title %}
                <p><b>Tytuł</b> jest polem wymaganym.</p>
            {% endif %}
            {% if error.spell_school %}
                <p><b>Szkoła magii</b> jest polem wymaganym.</p>
            {% endif %}
            {% if error.title %}
                <p><b>Opis</b> jest polem wymaganym</p>
            {% endif %}
        </div>
        {% endif %}
        <h2 class="text-center mb-4">Dodaj zaklęcie</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="form-floating">
                <input type="text" name="title" class="form-control" id="id_title" placeholder="Nazwa zaklęcia">
                <label for="id_title"><b>Nazwa</b></label>
            </div>

            <div class="row">
                <div class="col-md">
                    <div class="form-floating">
                        <select class="form-select" name="spell_school" id="id_spell_school" aria-placeholder="Wybierz szkołę">
                            {% for val, name in form.fields.spell_school.choices %}
                                <option value="{{ val }}">{{ name | capfirst }}</option>
                            {% endfor %}
                        </select>
                        <label for="id_spell_school"><b>Szkoła magii</b></label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <select class="form-select" name="spell_level" id="id_spell_level" aria-placeholder="Poziom zaklęcia">
                            {% for val, name in form.fields.spell_level.choices %}
                                <option value="{{ val }}">{{ name | capfirst }}</option>
                            {% endfor %}
                        </select>
                        <label for="id_spell_level">Poziom zaklęcia</label>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md">
                    <div class="form-floating">
                        <select class="form-select" name="casting_time" id="id_casting_time" aria-placeholder="Wybierz szkołę">
                            {% for val, name in form.fields.casting_time.choices %}
                                <option value="{{ val }}">{{ name | capfirst}}</option>
                            {% endfor %}
                        </select>
                        <label for="id_casting_time">Czas rzucania</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <select class="form-select" name="duration" id="id_duration" aria-placeholder="Poziom zaklęcia">
                            {% for val, name in form.fields.duration.choices %}
                                <option value="{{ val }}">{{ name | capfirst }}</option>
                            {% endfor %}
                        </select>
                        <label for="id_duration">Czas działania</label>
                    </div>
                </div>
            </div>

            <div class="form-floating">
                <input type="text" name="distance" class="form-control" id="id_distance" placeholder="Zasięg">
                <label for="id_distance">Zasięg</label>
            </div>

            <div class="row">
                <div class="col-md col-components">
                    {% for component in form.components %}
                        {{ component }}
                    {% endfor %}
                </div>
            </div>

            <div class="form-floating">
                <input type="text" name="material_description" class="form-control" id="id_material_description" placeholder="Nazwa zaklęcia">
                <label for="id_material_description">Opis materiałów</label>
            </div>

            <div class="row">
                <div class="col-md">
                    <input class="form-check-input" type="checkbox" name="ritual" value="" id="id_ritual">
                    <label class="form-check-label" for="id_ritual">
                        Rytuał
                    </label>
                </div>
                <div class="col-md">
                    <input class="form-check-input" type="checkbox" name="concentration" value="" id="id_concentration">
                    <label class="form-check-label" for="id_concentration">
                        Wymaga koncentracji
                    </label>
                </div>
            </div>
            
            <div class="form-floating">
                {{ form.description }}
                {{ form.media }}
            </div>
            <div class="form-floating">
                <textarea type="text" name="higher_level" class="form-control" id="id_higher_level" rows=4 placeholder="Wprowadź opis dla wyższych poziomów"></textarea>
                <label for="id_higher_level">Na wyższym poziomie</label>
            </div>
            <button type="submit" class="btn btn-spell">Dodaj</button>
        </form>
    </div>
</div>
{% endblock %}

spell/templates/spell/show_all_spells.html
{% extends 'base.html' %}

{% block content %}
<h1>Show all spells</h1>
{% endblock %}